### ISSUE TITLE
working-directory

### ISSUE THREAD

**Issue by craig-dae** [dhollerbach/actions.serverless-with-python-requirements#10]
Is there a way to do this with a `working-directory` option? Our serverless.yml is not in the root of the project.

**Comment by dhollerbach** [comment]
I'm sure that could be added, though it is certainly easiest to have your serverless.yml at your root level if possible.

**Comment by clarencenpy** [comment]
@craig-dae As a workaround, you could specify the location of your `serverless.yml` file using `--config` flag. 
```
- name: Serverless Deploy
        uses: dhollerbach/github-action-serverless-with-python-requirements@master
        with:
          args: "--stage dev --config path/to/your/serverless.yml"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
