### ISSUE TITLE
don't accept --stage option

### ISSUE THREAD

**Issue by elgreatly** [dhollerbach/actions.serverless-with-python-requirements#14]
when i add `--stage` in `args` i got this issue `Detected unrecognized CLI options: "--stage"`
```
- name: Serverless Deploy
   uses: dhollerbach/actions.serverless-with-python-requirements@master
   with:
      args: --stage dev --verbose
   env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
```

should i do something else to be able working with `--stage` option?

**Comment by porthunt** [comment]
I stopped using this and solved my problem using:

```yaml
steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up environment
        run: npm install

      - name: Serverless Deploy
        run: npx serverless deploy --stage dev --conceal
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
